package com.rockettest.biblioetca.mapper;

import com.rockettest.biblioetca.model.Author;
import com.rockettest.biblioetca.model.AuthorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    long countByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insert(Author row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insertSelective(Author row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    List<Author> selectByExampleWithBLOBs(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    List<Author> selectByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    Author selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExampleSelective(@Param("row") Author row, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") Author row, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExample(@Param("row") Author row, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKeySelective(Author row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(Author row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKey(Author row);
}