package com.rockettest.biblioetca.mapper;

import com.rockettest.biblioetca.model.Book;
import com.rockettest.biblioetca.model.BookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insert(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insertSelective(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    Book selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExampleSelective(@Param("row") Book row, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExample(@Param("row") Book row, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKeySelective(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOKS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKey(Book row);
}