package com.rockettest.biblioetca.mapper;

import com.rockettest.biblioetca.model.BookCopy;
import com.rockettest.biblioetca.model.BookCopyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    long countByExample(BookCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByExample(BookCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insert(BookCopy row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insertSelective(BookCopy row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    List<BookCopy> selectByExample(BookCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    BookCopy selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExampleSelective(@Param("row") BookCopy row, @Param("example") BookCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExample(@Param("row") BookCopy row, @Param("example") BookCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKeySelective(BookCopy row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_COPIES
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKey(BookCopy row);
}