package com.rockettest.biblioetca.mapper;

import com.rockettest.biblioetca.model.BookLoan;
import com.rockettest.biblioetca.model.BookLoanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    long countByExample(BookLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByExample(BookLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insert(BookLoan row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insertSelective(BookLoan row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    List<BookLoan> selectByExample(BookLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    BookLoan selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExampleSelective(@Param("row") BookLoan row, @Param("example") BookLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExample(@Param("row") BookLoan row, @Param("example") BookLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKeySelective(BookLoan row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOK_LOANS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKey(BookLoan row);
}