package com.rockettest.biblioetca.mapper;

import com.rockettest.biblioetca.model.Publisher;
import com.rockettest.biblioetca.model.PublisherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublisherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    long countByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int deleteByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int insert(Publisher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int insertSelective(Publisher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    List<Publisher> selectByExample(PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    Publisher selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int updateByExampleSelective(@Param("row") Publisher row, @Param("example") PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int updateByExample(@Param("row") Publisher row, @Param("example") PublisherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int updateByPrimaryKeySelective(Publisher row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISHERS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    int updateByPrimaryKey(Publisher row);
}