package com.rockettest.biblioetca.mapper;

import com.rockettest.biblioetca.model.Student;
import com.rockettest.biblioetca.model.StudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insert(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int insertSelective(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    Student selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExampleSelective(@Param("row") Student row, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByExample(@Param("row") Student row, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKeySelective(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    int updateByPrimaryKey(Student row);
}