package com.rockettest.biblioetca.model;

import java.util.Date;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORS.NAME
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORS.BIOGRAPHY
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String biography;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORS.ID
     *
     * @return the value of AUTHORS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORS.ID
     *
     * @param id the value for AUTHORS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORS.NAME
     *
     * @return the value of AUTHORS.NAME
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORS.NAME
     *
     * @param name the value for AUTHORS.NAME
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORS.CREATED_AT
     *
     * @return the value of AUTHORS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORS.CREATED_AT
     *
     * @param createdAt the value for AUTHORS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORS.BIOGRAPHY
     *
     * @return the value of AUTHORS.BIOGRAPHY
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getBiography() {
        return biography;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORS.BIOGRAPHY
     *
     * @param biography the value for AUTHORS.BIOGRAPHY
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setBiography(String biography) {
        this.biography = biography;
    }
}