package com.rockettest.biblioetca.model;

import java.util.Date;

public class BookCopy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_COPIES.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_COPIES.BOOK_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_COPIES.PUBLISHER_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_COPIES.STATUS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_COPIES.CONDITION
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_COPIES.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_COPIES.ID
     *
     * @return the value of BOOK_COPIES.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_COPIES.ID
     *
     * @param id the value for BOOK_COPIES.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_COPIES.BOOK_ID
     *
     * @return the value of BOOK_COPIES.BOOK_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_COPIES.BOOK_ID
     *
     * @param bookId the value for BOOK_COPIES.BOOK_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setBookId(Short bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_COPIES.PUBLISHER_ID
     *
     * @return the value of BOOK_COPIES.PUBLISHER_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_COPIES.PUBLISHER_ID
     *
     * @param publisherId the value for BOOK_COPIES.PUBLISHER_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setPublisherId(Short publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_COPIES.STATUS
     *
     * @return the value of BOOK_COPIES.STATUS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_COPIES.STATUS
     *
     * @param status the value for BOOK_COPIES.STATUS
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_COPIES.CONDITION
     *
     * @return the value of BOOK_COPIES.CONDITION
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_COPIES.CONDITION
     *
     * @param condition the value for BOOK_COPIES.CONDITION
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_COPIES.CREATED_AT
     *
     * @return the value of BOOK_COPIES.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_COPIES.CREATED_AT
     *
     * @param createdAt the value for BOOK_COPIES.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}