package com.rockettest.biblioetca.model;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.TITLE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.ISBN
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.PUBLICATION_YEAR
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short publicationYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.CATEGORY
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.IMAGE_URL
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.PUBLISHER_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.AUTHOR_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOKS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.ID
     *
     * @return the value of BOOKS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.ID
     *
     * @param id the value for BOOKS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.TITLE
     *
     * @return the value of BOOKS.TITLE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.TITLE
     *
     * @param title the value for BOOKS.TITLE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.ISBN
     *
     * @return the value of BOOKS.ISBN
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.ISBN
     *
     * @param isbn the value for BOOKS.ISBN
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.PUBLICATION_YEAR
     *
     * @return the value of BOOKS.PUBLICATION_YEAR
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getPublicationYear() {
        return publicationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.PUBLICATION_YEAR
     *
     * @param publicationYear the value for BOOKS.PUBLICATION_YEAR
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setPublicationYear(Short publicationYear) {
        this.publicationYear = publicationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.CATEGORY
     *
     * @return the value of BOOKS.CATEGORY
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.CATEGORY
     *
     * @param category the value for BOOKS.CATEGORY
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.IMAGE_URL
     *
     * @return the value of BOOKS.IMAGE_URL
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.IMAGE_URL
     *
     * @param imageUrl the value for BOOKS.IMAGE_URL
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.PUBLISHER_ID
     *
     * @return the value of BOOKS.PUBLISHER_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.PUBLISHER_ID
     *
     * @param publisherId the value for BOOKS.PUBLISHER_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setPublisherId(Short publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.AUTHOR_ID
     *
     * @return the value of BOOKS.AUTHOR_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.AUTHOR_ID
     *
     * @param authorId the value for BOOKS.AUTHOR_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setAuthorId(Short authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOKS.CREATED_AT
     *
     * @return the value of BOOKS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOKS.CREATED_AT
     *
     * @param createdAt the value for BOOKS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}