package com.rockettest.biblioetca.model;

import java.util.Date;

public class BookLoan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_LOANS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_LOANS.BOOK_COPY_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short bookCopyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_LOANS.STUDENT_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Short studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_LOANS.LOAN_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Date loanDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_LOANS.DUE_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK_LOANS.RETURN_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    private Date returnDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_LOANS.ID
     *
     * @return the value of BOOK_LOANS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_LOANS.ID
     *
     * @param id the value for BOOK_LOANS.ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_LOANS.BOOK_COPY_ID
     *
     * @return the value of BOOK_LOANS.BOOK_COPY_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getBookCopyId() {
        return bookCopyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_LOANS.BOOK_COPY_ID
     *
     * @param bookCopyId the value for BOOK_LOANS.BOOK_COPY_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setBookCopyId(Short bookCopyId) {
        this.bookCopyId = bookCopyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_LOANS.STUDENT_ID
     *
     * @return the value of BOOK_LOANS.STUDENT_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Short getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_LOANS.STUDENT_ID
     *
     * @param studentId the value for BOOK_LOANS.STUDENT_ID
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setStudentId(Short studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_LOANS.LOAN_DATE
     *
     * @return the value of BOOK_LOANS.LOAN_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Date getLoanDate() {
        return loanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_LOANS.LOAN_DATE
     *
     * @param loanDate the value for BOOK_LOANS.LOAN_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setLoanDate(Date loanDate) {
        this.loanDate = loanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_LOANS.DUE_DATE
     *
     * @return the value of BOOK_LOANS.DUE_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_LOANS.DUE_DATE
     *
     * @param dueDate the value for BOOK_LOANS.DUE_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK_LOANS.RETURN_DATE
     *
     * @return the value of BOOK_LOANS.RETURN_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK_LOANS.RETURN_DATE
     *
     * @param returnDate the value for BOOK_LOANS.RETURN_DATE
     *
     * @mbg.generated Wed May 28 21:17:34 CST 2025
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }
}