package com.rockettest.biblioetca.model;

import java.util.Date;

public class Publisher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLISHERS.ID
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLISHERS.NAME
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLISHERS.PHONE
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLISHERS.EMAIL
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLISHERS.ADDRESS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLISHERS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLISHERS.ID
     *
     * @return the value of PUBLISHERS.ID
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLISHERS.ID
     *
     * @param id the value for PUBLISHERS.ID
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLISHERS.NAME
     *
     * @return the value of PUBLISHERS.NAME
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLISHERS.NAME
     *
     * @param name the value for PUBLISHERS.NAME
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLISHERS.PHONE
     *
     * @return the value of PUBLISHERS.PHONE
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLISHERS.PHONE
     *
     * @param phone the value for PUBLISHERS.PHONE
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLISHERS.EMAIL
     *
     * @return the value of PUBLISHERS.EMAIL
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLISHERS.EMAIL
     *
     * @param email the value for PUBLISHERS.EMAIL
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLISHERS.ADDRESS
     *
     * @return the value of PUBLISHERS.ADDRESS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLISHERS.ADDRESS
     *
     * @param address the value for PUBLISHERS.ADDRESS
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLISHERS.CREATED_AT
     *
     * @return the value of PUBLISHERS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLISHERS.CREATED_AT
     *
     * @param createdAt the value for PUBLISHERS.CREATED_AT
     *
     * @mbg.generated Wed May 28 21:17:33 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}